/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
                    "colors": {
                        "on-primary-fixed-variant": "#3c4d00",
                        "surface-container-high": "#2a2a2a",
                        "primary-fixed": "#c3f400",
                        "on-secondary": "#68000e",
                        "primary-fixed-dim": "#abd600",
                        "error": "#ffb4ab",
                        "outline": "#8e9379",
                        "on-error": "#690005",
                        "surface-container-lowest": "#0e0e0e",
                        "on-primary-container": "#556d00",
                        "background": "#131313",
                        "on-tertiary-fixed-variant": "#454747",
                        "surface-container-low": "#1c1b1b",
                        "on-primary-fixed": "#161e00",
                        "on-background": "#e5e2e1",
                        "inverse-surface": "#e5e2e1",
                        "secondary-container": "#ff5357",
                        "surface-bright": "#3a3939",
                        "primary": "#ffffff",
                        "tertiary-fixed-dim": "#c6c6c7",
                        "surface-container": "#201f1f",
                        "surface-dim": "#131313",
                        "secondary-fixed": "#ffdad8",
                        "on-tertiary-fixed": "#1a1c1c",
                        "on-tertiary-container": "#636565",
                        "on-error-container": "#ffdad6",
                        "on-surface": "#e5e2e1",
                        "on-tertiary": "#2f3131",
                        "on-surface-variant": "#c4c9ac",
                        "tertiary-fixed": "#e2e2e2",
                        "tertiary": "#ffffff",
                        "outline-variant": "#444933",
                        "secondary": "#ffb3af",
                        "tertiary-container": "#e2e2e2",
                        "inverse-primary": "#506600",
                        "on-secondary-container": "#5c000b",
                        "error-container": "#93000a",
                        "inverse-on-surface": "#313030",
                        "on-secondary-fixed": "#410006",
                        "surface": "#131313",
                        "primary-container": "#c3f400",
                        "surface-tint": "#abd600",
                        "on-secondary-fixed-variant": "#930019",
                        "secondary-fixed-dim": "#ffb3af",
                        "surface-variant": "#353534",
                        "surface-container-highest": "#353534",
                        "on-primary": "#283500"
                    },
                    "fontFamily": {
                        "label-bold": ["Space Grotesk"],
                        "headline-md": ["Lexend"],
                        "display-xl": ["Lexend"],
                        "stats-num": ["Space Grotesk"],
                        "headline-lg": ["Lexend"],
                        "body-md": ["Inter"],
                        "body-lg": ["Inter"]
                    },
                    "fontSize": {
                        "label-bold": ["14px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "700"}],
                        "headline-md": ["32px", {"lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
                        "display-xl": ["80px", {"lineHeight": "72px", "letterSpacing": "-0.04em", "fontWeight": "900"}],
                        "stats-num": ["24px", {"lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
                        "headline-lg": ["48px", {"lineHeight": "52px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
                        "body-md": ["16px", {"lineHeight": "24px", "letterSpacing": "0", "fontWeight": "400"}],
                        "body-lg": ["18px", {"lineHeight": "28px", "letterSpacing": "0", "fontWeight": "400"}]
                    }
                },
  },
  plugins: [],
}
